
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
MOUSEKEY_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
LED_MATRIX_ENABLE = no